docker: add aws bases

diff --git a/docker/Dockerfile.amd b/docker/Dockerfile.amd
--- a/docker/Dockerfile.amd
+++ b/docker/Dockerfile.amd
@@ -3,21 +3,57 @@
 # Based on  https://github.com/amd/InfinityHub-CI/tree/main/base-gpu-mpi-rocm-docker
 ##############################################################
 
+ARG base=rocm/dev-ubuntu-22.04
 ARG ROCM_VERSION=7.0.2
-
-FROM rocm/dev-ubuntu-22.04:${ROCM_VERSION}-complete AS sdk-base
-
 ARG UCX_BRANCH="v1.17.x"
 ARG OMPI_BRANCH="v5.0.x"
 
-# Update and Install basic Linux development tools
-RUN rm /etc/apt/sources.list.d/* \
-  && apt-get update \
-  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-    dh-autoreconf python3-venv python3-dev python3-pip git \
-    ca-certificates ssh make libtinfo* initramfs-tools libelf-dev \
-    wget build-essential autoconf automake libtool \
-    pkg-config libnuma* gfortran flex hwloc cmake
+FROM rocm/dev-fedora-24:${ROCM_VERSION}-complete AS rocm-fedora
+
+FROM ${base}:${ROCM_VERSION}-complete AS sdk-base
+
+SHELL ["/bin/bash", "-c"]
+
+ARG ROCM_VERSION
+ARG UCX_BRANCH
+ARG OMPI_BRANCH
+
+COPY requirements-mpi.txt /tmp/requirements-mpi.txt
+COPY --from=rocm-fedora /opt/rocm /opt/rocm-fedora
+
+# Install development dependencies
+RUN if command -v apt-get >/dev/null; then \
+        export DEBIAN_FRONTEND=noninteractive && \
+        rm /etc/apt/sources.list.d/* && \
+        apt-get update && \
+        apt-get install -y --no-install-recommends \
+            dh-autoreconf python3-venv python3-dev python3-pip git \
+            ca-certificates ssh make libtinfo* initramfs-tools libelf-dev \
+            wget build-essential autoconf automake libtool \
+            pkg-config libnuma* gfortran flex hwloc cmake \
+            libncurses5-dev libncursesw5-dev libdrm-dev libsystemd-dev \
+            python3-dbg gdb numactl tmux vim libgl1-mesa-glx libfftw3-dev; \
+    else \
+        dnf update -y && \
+        dnf install -y \
+            python3 python3-devel python3-pip git ca-certificates \
+            make automake autoconf libtool cmake \
+            numactl numactl-devel hwloc hwloc-devel flex wget \
+            gcc gcc-c++ gcc-gfortran pkgconfig \
+            ncurses-devel libdrm-devel systemd-devel gdb numactl tmux vim mesa-libGL fftw-devel && \
+        (dnf install -y python3-debug || true) && \
+        dnf clean all && rm -rf /var/cache/dnf; \
+    fi
+
+# Provide ROCm on RPM bases using Fedora artifacts
+RUN if command -v apt-get >/dev/null; then \
+        rm -rf /opt/rocm-fedora; \
+    else \
+        rm -rf /opt/rocm && \
+        mkdir -p /opt/rocm && \
+        cp -a /opt/rocm-fedora/. /opt/rocm/ && \
+        rm -rf /opt/rocm-fedora; \
+    fi
 
 ENV ROCM_HOME=/opt/rocm\
     UCX_HOME=/opt/ucx \
@@ -79,13 +115,27 @@ ENV UCX_WARN_UNUSED_ENV_VARS=n
 ENV UCX_TLS=sm,self,rocm,rocm_copy,rocm_ipc
 
 # Cleanup
-RUN rm -rf /tmp/ucx && rm -rf /tmp/ompi
+RUN rm -rf /tmp/ucx /tmp/ompi
+
+# Python virtual environment with mpi4py
+RUN python3 -m venv /venv && \
+    /venv/bin/pip install --no-cache-dir --upgrade pip wheel setuptools && \
+    MPICC=$OMPI_HOME/bin/mpicc /venv/bin/pip install --no-cache-dir -r /tmp/requirements-mpi.txt && \
+    /venv/bin/pip install --no-cache-dir jupyter && \
+    rm -rf ~/.cache/pip
+
+# Cleanup package caches
+RUN if command -v apt-get >/dev/null; then \
+        apt-get clean && apt-get autoclean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*; \
+    else \
+        true; \
+    fi
 
 # Adding OpenMPI and UCX to Environment
 ENV PATH=$OMPI_HOME/bin:$UCX_HOME/bin:$PATH \
     LD_LIBRARY_PATH=$OMPI_HOME/lib:$UCX_HOME/lib:$LD_LIBRARY_PATH \
-    C_INCLUDE_PATH=$OMPI_HOME/include:$UCX_HOME/include:$C_INCLUDE_PATH \ 
-    CPLUS_INCLUDE_PATH=$OMPI_HOME/include:$UCX_HOME/include:$CPLUS_INCLUDE_PATH \ 
+    C_INCLUDE_PATH=$OMPI_HOME/include:$UCX_HOME/include:$C_INCLUDE_PATH \
+    CPLUS_INCLUDE_PATH=$OMPI_HOME/include:$UCX_HOME/include:$CPLUS_INCLUDE_PATH \
     CPATH=$OMPI_HOME/include:$UCX_HOME/include:$CPATH \
     INCLUDE=$OMPI_HOME/include:$UCX_HOME/include:$INCLUDE \
     PKG_CONFIG_PATH=$OMPI_HOME/lib/pkgconfig:$UCX_HOME/lib/pkgconfig:$PKG_CONFIG_PATH
@@ -93,9 +143,6 @@ ENV PATH=$OMPI_HOME/bin:$UCX_HOME/bin:$PATH \
 # Adding environment variable for Running as ROOT
 ENV OMPI_ALLOW_RUN_AS_ROOT=1
 ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
-
-RUN apt-get clean && apt-get autoclean && apt-get autoremove -y && \
-    rm -rf /var/lib/apt/lists/*
 
 EXPOSE 8888
 CMD ["/bin/bash"]
diff --git a/docker/Dockerfile.cpu b/docker/Dockerfile.cpu
--- a/docker/Dockerfile.cpu
+++ b/docker/Dockerfile.cpu
@@ -4,24 +4,43 @@
 # architectures using GCC compilers and OpenMPI.
 ##############################################################
 
-# Base image 
-FROM ubuntu:22.04 AS base
-
+ARG base=ubuntu:22.04
 ARG gcc=""
+ARG OMPI_BRANCH="v5.0.x"
 
-ENV DEBIAN_FRONTEND=noninteractive
+FROM ${base} AS base
 
-# Install python
-RUN apt-get update && \
-    apt-get install -y software-properties-common dh-autoreconf python3-venv python3-dev python3-pip
+SHELL ["/bin/bash", "-c"]
 
-# Install for basic base not containing it
-RUN apt-get install -y wget flex libnuma-dev hwloc curl cmake git \
-        autoconf libtool build-essential procps software-properties-common
+ARG gcc
+ARG OMPI_BRANCH
 
-# Install gcc
+COPY requirements-mpi.txt /tmp/requirements-mpi.txt
+
+# Install prerequisites
+RUN if command -v apt-get >/dev/null; then \
+        export DEBIAN_FRONTEND=noninteractive && \
+        apt-get update && \
+        apt-get install -y \
+            software-properties-common dh-autoreconf python3-venv python3-dev python3-pip \
+            wget flex libnuma-dev hwloc curl cmake git \
+            autoconf libtool build-essential procps \
+            libgmp-dev libmpc-dev libmpfr-dev libisl-dev binutils texinfo \
+            libncurses5-dev libncursesw5-dev libdrm-dev libsystemd-dev \
+            python3-dbg gdb numactl tmux vim libgl1-mesa-glx libfftw3-dev; \
+    else \
+        dnf update -y && \
+        dnf install -y \
+            python3 python3-devel python3-pip \
+            wget flex numactl-devel hwloc hwloc-devel curl cmake git \
+            autoconf libtool make which procps-ng gcc gcc-c++ gcc-gfortran \
+            gmp-devel libmpc-devel mpfr-devel isl-devel binutils texinfo \
+            ncurses-devel libdrm-devel systemd-devel gdb numactl tmux vim mesa-libGL fftw-devel && \
+        (dnf install -y python3-debug || true); \
+    fi
+
+# Optional GCC from source
 RUN if [ -n "$gcc" ]; then \
-        apt-get install libgmp-dev libmpc-dev libmpfr-dev libisl-dev binutils texinfo -y && \
         cd /tmp && mkdir gcc && \
         git clone git://gcc.gnu.org/git/gcc.git gcc && \
         cd gcc && git checkout releases/gcc-${gcc} && \
@@ -29,32 +48,45 @@ RUN if [ -n "$gcc" ]; then \
         ../configure --prefix=/opt/gcc-${gcc} --enable-languages=c,c++,fortran --disable-multilib \
                     --enable-shared --enable-lto --enable-libstdcxx-time=yes --enable-libgomp && \
         make -j $(nproc) && make install-strip && \
-        # Update alternatives
-        update-alternatives --install /usr/bin/gcc gcc /opt/gcc-${gcc}/bin/gcc 60 && \
-        update-alternatives --install /usr/bin/g++ g++ /opt/gcc-${gcc}/bin/g++ 60 && \
-        update-alternatives --install /usr/bin/gfortran gfortran /opt/gcc-${gcc}/bin/gfortran 60 && \
+        if command -v update-alternatives >/dev/null; then \
+            update-alternatives --install /usr/bin/gcc gcc /opt/gcc-${gcc}/bin/gcc 60 && \
+            update-alternatives --install /usr/bin/g++ g++ /opt/gcc-${gcc}/bin/g++ 60 && \
+            update-alternatives --install /usr/bin/gfortran gfortran /opt/gcc-${gcc}/bin/gfortran 60; \
+        else \
+            alternatives --install /usr/bin/gcc gcc /opt/gcc-${gcc}/bin/gcc 60 && \
+            alternatives --install /usr/bin/g++ g++ /opt/gcc-${gcc}/bin/g++ 60 && \
+            alternatives --install /usr/bin/gfortran gfortran /opt/gcc-${gcc}/bin/gfortran 60; \
+        fi && \
         rm -rf /tmp/gcc; \
-    fi;
+    fi
 
-ARG OMPI_BRANCH="v5.0.x"
 # Install OpenMPI
 RUN cd /tmp && mkdir openmpi && \
     git clone --depth 1 --recursive --branch ${OMPI_BRANCH} https://github.com/open-mpi/ompi.git openmpi && \
     cd openmpi && ./autogen.pl && \
-    mkdir build &&  cd build && \
+    mkdir build && cd build && \
     ../configure --prefix=/opt/openmpi/ \
                  --disable-mpi-fortran \
                  --enable-mca-no-build=btl-uct --enable-mpi1-compatibility && \
     make -j ${nproc} && \
     make install && \
-    cd /tmp && rm -rf /tmp/openmpi
+    rm -rf /tmp/openmpi
+
+# Python virtual environment with mpi4py
+RUN python3 -m venv /venv && \
+    /venv/bin/pip install --no-cache-dir --upgrade pip wheel setuptools && \
+    MPICC=/opt/openmpi/bin/mpicc /venv/bin/pip install --no-cache-dir -r /tmp/requirements-mpi.txt
 
 # Set OpenMPI path
 ENV PATH=${PATH}:/opt/openmpi/bin
 ENV LD_LIBRARY_PATH=/opt/openmpi/lib
 
-# Cleanup
-RUN apt-get clean && apt-get autoclean && apt-get autoremove  -y && rm -rf /var/lib/apt/lists/*
+# Cleanup package caches
+RUN if command -v apt-get >/dev/null; then \
+        apt-get clean && apt-get autoclean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*; \
+    else \
+        dnf clean all && rm -rf /var/cache/dnf; \
+    fi
 
 EXPOSE 8888
 CMD ["/bin/bash"]
diff --git a/docker/Dockerfile.intel b/docker/Dockerfile.intel
--- a/docker/Dockerfile.intel
+++ b/docker/Dockerfile.intel
@@ -3,58 +3,77 @@
 # This Dockerfile contains the Intel OneAPI toolkit for Devito
 ##############################################################
 
-# Base image
-FROM ubuntu:22.04 as base
+ARG base=ubuntu:22.04
 
-ENV DEBIAN_FRONTEND noninteractive
+FROM ${base} as oneapi
 
-# Install python
-RUN apt-get update && \
-    apt-get install -y dh-autoreconf python3-venv python3-dev python3-pip
+SHELL ["/bin/bash", "-c"]
 
-# Install for basic base not containing it
-RUN apt-get install -y wget flex libnuma-dev hwloc curl cmake \
-        autoconf libtool build-essential procps git
+COPY requirements-mpi.txt /tmp/requirements-mpi.txt
 
-EXPOSE 8888
-CMD ["/bin/bash"]
+# Install base dependencies
+RUN if command -v apt-get >/dev/null; then \
+        export DEBIAN_FRONTEND=noninteractive && \
+        apt-get update && \
+        apt-get install -y \
+            dh-autoreconf python3-venv python3-dev python3-pip \
+            wget flex libnuma-dev hwloc curl cmake \
+            autoconf libtool build-essential procps git gpg \
+            libncurses5-dev libncursesw5-dev libdrm-dev libsystemd-dev \
+            python3-dbg gdb numactl tmux vim libgl1-mesa-glx libfftw3-dev; \
+    else \
+        dnf update -y && \
+        dnf install -y \
+            python3 python3-devel python3-pip \
+            wget flex numactl-devel hwloc hwloc-devel curl cmake \
+            git autoconf libtool make which procps-ng gcc gcc-c++ gcc-gfortran \
+            gpgme ncurses-devel libdrm-devel systemd-devel gdb numactl tmux vim mesa-libGL fftw-devel && \
+        (dnf install -y python3-debug || true) && \
+        dnf clean all && rm -rf /var/cache/dnf; \
+    fi
 
-##############################################################
-# Intel OneAPI standard image
-##############################################################
-FROM base AS oneapi
-
-# Download the key to system keyring
-# https://www.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-linux/top/installation/install-using-package-managers/apt.html#apt
-RUN wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor > /usr/share/keyrings/oneapi-archive-keyring.gpg
-RUN echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" > /etc/apt/sources.list.d/oneAPI.list
-
-# Intel advisor and drivers
-RUN apt-get update -y && \
-    # advisor
-    apt-get install -y intel-oneapi-advisor
-
-# Drivers mandatory for intel gpu
-# https://dgpu-docs.intel.com/driver/installation.html#ubuntu-install-steps
-RUN wget -qO - https://repositories.intel.com/graphics/intel-graphics.key | gpg --dearmor > /usr/share/keyrings/intel-graphics.gpg
-RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/graphics/ubuntu jammy unified" >  /etc/apt/sources.list.d/intel-gpu-jammy.list
-
-RUN apt-get update -y && apt-get dist-upgrade -y && \
-    # Compute and media runtime
-    apt-get install -y intel-opencl-icd intel-level-zero-gpu level-zero \
+# Configure Intel repositories and install toolkits
+RUN if command -v apt-get >/dev/null; then \
+        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor > /usr/share/keyrings/oneapi-archive-keyring.gpg && \
+        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" > /etc/apt/sources.list.d/oneAPI.list && \
+        wget -qO - https://repositories.intel.com/graphics/intel-graphics.key | gpg --dearmor > /usr/share/keyrings/intel-graphics.gpg && \
+        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/graphics/ubuntu jammy unified" > /etc/apt/sources.list.d/intel-gpu-jammy.list && \
+        apt-get update -y && apt-get dist-upgrade -y && \
+        apt-get install -y intel-oneapi-advisor && \
+        apt-get install -y intel-oneapi-mpi-devel && \
+        apt-get install -y intel-opencl-icd intel-level-zero-gpu level-zero \
             intel-media-va-driver-non-free libmfx1 libmfxgen1 libvpl2 \
             libegl-mesa0 libegl1-mesa libegl1-mesa-dev libgbm1 libgl1-mesa-dev libgl1-mesa-dri \
             libglapi-mesa libgles2-mesa-dev libglx-mesa0 libigdgmm12 libxatracker2 mesa-va-drivers \
             mesa-vdpau-drivers mesa-vulkan-drivers va-driver-all vainfo hwinfo clinfo \
-            # XPU-SMI
             pciutils libkmod-dev intel-fw-gpu xpu-smi \
-            # Development packages
-            libigc-dev intel-igc-cm libigdfcl-dev libigfxcmrt-dev level-zero-dev
+            libigc-dev intel-igc-cm libigdfcl-dev libigfxcmrt-dev level-zero-dev; \
+    else \
+        dnf install -y dnf-plugins-core && \
+        dnf config-manager --add-repo https://yum.repos.intel.com/oneapi && \
+        rpm --import https://yum.repos.intel.com/oneapi/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB && \
+        dnf update -y && \
+        dnf install -y intel-oneapi-advisor && \
+        dnf install -y intel-oneapi-mpi-devel intel-oneapi-runtime-compilers intel-oneapi-runtime-dpcpp-cpp \
+            intel-oneapi-runtime-opencl intel-oneapi-runtime-level-zero && \
+        dnf clean all && rm -rf /var/cache/dnf; \
+    fi
 
-ENV MPI4PY_FLAGS='. /opt/intel/oneapi/setvars.sh intel64 && '
+# Python virtual environment with mpi4py pre-installed
+RUN python3 -m venv /venv && \
+    /venv/bin/pip install --no-cache-dir --upgrade pip wheel setuptools && \
+    source /opt/intel/oneapi/setvars.sh intel64 && \
+    MPICC=mpiicc /venv/bin/pip install --no-cache-dir -r /tmp/requirements-mpi.txt
+
 ENV MPI4PY_RC_RECV_MPROBE=0
 
-RUN apt-get clean && apt-get autoclean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*
+# Cleanup package caches on apt-based systems
+RUN if command -v apt-get >/dev/null; then \
+        apt-get clean && apt-get autoclean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*; \
+    fi
+
+EXPOSE 8888
+CMD ["/bin/bash"]
 
 ##############################################################
 # ICC image
@@ -62,9 +81,14 @@ RUN apt-get clean && apt-get autoclean && apt-get autoremove -y && rm -rf /var/l
 ##############################################################
 FROM oneapi AS icc
 
-RUN apt-get update -y && apt-get install -y intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-mpi-devel && \
-    apt-get clean && apt-get autoclean && apt-get autoremove -y && \
-    rm -rf /var/lib/apt/lists/*
+RUN if command -v apt-get >/dev/null; then \
+        apt-get update -y && \
+        apt-get install -y intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-mpi-devel && \
+        apt-get clean && apt-get autoclean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*; \
+    else \
+        dnf install -y intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-mpi-devel && \
+        dnf clean all && rm -rf /var/cache/dnf; \
+    fi
 
 # Devito config
 ENV I_MPI_CC="icc"
@@ -80,9 +104,14 @@ ENV MPICC=mpiicc
 ##############################################################
 FROM oneapi AS icx
 
-RUN apt-get update -y && apt-get install -y intel-oneapi-compiler-dpcpp-cpp intel-oneapi-mpi-devel && \
-    apt-get clean && apt-get autoclean && apt-get autoremove -y && \
-    rm -rf /var/lib/apt/lists/*
+RUN if command -v apt-get >/dev/null; then \
+        apt-get update -y && \
+        apt-get install -y intel-oneapi-compiler-dpcpp-cpp intel-oneapi-mpi-devel && \
+        apt-get clean && apt-get autoclean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*; \
+    else \
+        dnf install -y intel-oneapi-compiler-dpcpp-cpp intel-oneapi-mpi-devel && \
+        dnf clean all && rm -rf /var/cache/dnf; \
+    fi
 
 # Devito config
 ENV I_MPI_CC="icx"
diff --git a/docker/Dockerfile.nvidia b/docker/Dockerfile.nvidia
--- a/docker/Dockerfile.nvidia
+++ b/docker/Dockerfile.nvidia
@@ -1,50 +1,84 @@
 ##############################################################
 # This Dockerfile contains the NVidia HPC SDK (nvc, cuda, OpenMPI) for Devito
 ##############################################################
+ARG base=ubuntu:22.04
 ARG ver
 ARG arch="nvc"
 
 ########################################################################
-# Build base image with apt setup and common env
+# Build base image with common env
 ########################################################################
-FROM ubuntu:22.04 AS sdk-base
+FROM ${base} AS sdk-base
 
 SHELL ["/bin/bash", "-c"]
 
-ENV DEBIAN_FRONTEND noninteractive
-
-# Install python
-RUN apt-get update && \
-    apt-get install -y -q gpg apt-utils curl wget libnuma-dev cmake git \
-                          dh-autoreconf python3-venv python3-dev python3-pip
-
-# nodesource: nvdashboard requires nodejs>=10
-RUN curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | gpg --yes --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg
-RUN echo 'deb [trusted=yes, signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | tee /etc/apt/sources.list.d/nvhpc.list
-RUN apt-key update *&& apt-get update -y
-
-# Install nvhpc. `nvhpc` is the alias for the latest avaialble version
 ARG ver=nvhpc
-# We use the standard apt-get for the default latest nvhpc. For earlier version, apt has a bug that it will always
-# install the latest nvhpc-x-y no matter which version nvhpc-x-z is requested which would double (extra 10Gb) the size of the image.
-# So for specific version we directly download the specific deb and install it.
-RUN if [ "$ver" = "nvhpc" ]; then \
-        apt-get install -y -q --allow-unauthenticated ${ver}; \
-    else \
-        export year=$(echo $ver | cut -d "-" -f 2) && export minor=$(echo $ver | cut -d "-" -f 3) && \
-        wget https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64/nvhpc_${year}.${minor}_amd64.deb && \
-        apt-get install --allow-unauthenticated -y -q ./nvhpc_${year}.${minor}_amd64.deb; \
-    fi;
+ARG arch
 
-# Nodejs https://github.com/nodesource/distributions
-RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --yes --dearmor -o /etc/apt/keyrings/nodesource.gpg
-RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
-RUN apt-get update && apt-get install -y -q \
-        liblapack-dev libblas-dev \
-        libibverbs-dev libmlx4-1 libmlx5-1 ibutils \
-        # Devito Jupyter Notebooks and Ux experience
-        nodejs ffmpeg gcc-offload-nvptx \
-        texlive-latex-extra texlive-fonts-recommended dvipng cm-super
+COPY requirements-mpi.txt /tmp/requirements-mpi.txt
+
+# Install Python and system dependencies
+RUN if command -v apt-get >/dev/null; then \
+        export DEBIAN_FRONTEND=noninteractive && \
+        apt-get update && \
+        apt-get install -y -q gpg apt-utils curl wget libnuma-dev cmake git \
+            dh-autoreconf python3-venv python3-dev python3-pip \
+            libncurses5-dev libncursesw5-dev libdrm-dev libsystemd-dev \
+            python3-dbg gdb numactl tmux vim libgl1-mesa-glx libfftw3-dev; \
+    else \
+        dnf update -y && \
+        dnf install -y epel-release && \
+        dnf install -y python3 python3-devel python3-pip \
+            git gpgme wget curl numactl-devel hwloc hwloc-devel cmake \
+            gcc gcc-c++ gcc-gfortran make automake autoconf libtool which procps-ng \
+            openssl-devel libusbx libusbx-devel libstdc++-static \
+            ncurses-devel libdrm-devel systemd-devel gdb numactl tmux vim mesa-libGL fftw-devel && \
+        (dnf install -y python3-debug || true) && \
+        dnf clean all && rm -rf /var/cache/dnf; \
+    fi
+
+# Configure NVIDIA HPC SDK repositories and install toolchain
+RUN if command -v apt-get >/dev/null; then \
+        curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | gpg --yes --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg && \
+        echo 'deb [trusted=yes, signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | tee /etc/apt/sources.list.d/nvhpc.list && \
+        apt-key update && apt-get update -y && \
+        if [ "$ver" = "nvhpc" ]; then \
+            apt-get install -y -q --allow-unauthenticated ${ver}; \
+        else \
+            year=$(echo $ver | cut -d "-" -f 2) && minor=$(echo $ver | cut -d "-" -f 3) && \
+            wget https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64/nvhpc_${year}.${minor}_amd64.deb && \
+            apt-get install --allow-unauthenticated -y -q ./nvhpc_${year}.${minor}_amd64.deb; \
+        fi; \
+    else \
+        rpm --import https://developer.download.nvidia.com/hpc-sdk/RPM-GPG-KEY-NVIDIA-HPC-SDK && \
+        curl -fsSL https://developer.download.nvidia.com/hpc-sdk/nvhpc.repo -o /etc/yum.repos.d/nvhpc.repo && \
+        sed -i 's/$releasever/9/g' /etc/yum.repos.d/nvhpc.repo && \
+        dnf update -y && \
+        if [ -z "$ver" ] || [ "$ver" = "nvhpc" ]; then \
+            dnf install -y nvhpc; \
+        else \
+            dnf install -y ${ver}; \
+        fi && \
+        dnf clean all && rm -rf /var/cache/dnf; \
+    fi
+
+# Install additional runtime dependencies and Node.js
+RUN if command -v apt-get >/dev/null; then \
+        curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --yes --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
+        echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
+        apt-get update && \
+        apt-get install -y -q \
+            liblapack-dev libblas-dev \
+            libibverbs-dev libmlx4-1 libmlx5-1 ibutils \
+            nodejs ffmpeg gcc-offload-nvptx \
+            texlive-latex-extra texlive-fonts-recommended dvipng cm-super; \
+    else \
+        curl -fsSL https://rpm.nodesource.com/pub_18.x/nodesource-release-el9-1.noarch.rpm -o /tmp/nodesource.rpm && \
+        rpm -i /tmp/nodesource.rpm && \
+        dnf install -y nodejs ffmpeg texlive-scheme-basic rdma-core libibverbs && \
+        rm -f /tmp/nodesource.rpm && \
+        dnf clean all && rm -rf /var/cache/dnf; \
+    fi
 
 # nvidia-container-runtime
 ENV NVIDIA_VISIBLE_DEVICES all
@@ -113,17 +147,23 @@ ENV CPATH $HPCSDK_HOME/comm_libs/mpi/include:$HPCSDK_HOME/comm_libs/nvshmem/incl
 RUN rm -f  $HPCSDK_HOME/comm_libs/mpi && \
     ln -sf $HPCSDK_HOME/comm_libs/hpcx/latest/ompi $HPCSDK_HOME/comm_libs/mpi
 
-# Install python nvidia dependencies
+# Install python dependencies inside virtual environment
 RUN python3 -m venv /venv && \
     /venv/bin/pip install --no-cache-dir --upgrade pip && \
     /venv/bin/pip install --no-cache-dir -r https://raw.githubusercontent.com/devitocodes/devito/main/requirements-nvidia.txt && \
-    # Install jupyter and setup nvidia configs.
+    source /opt/nvhpc/comm_libs/hpcx/latest/hpcx-init.sh && \
+    hpcx_load && \
+    MPICC=mpicc /venv/bin/pip install --no-cache-dir -r /tmp/requirements-mpi.txt && \
     /venv/bin/pip install --no-cache-dir jupyter && \
     /venv/bin/jupyter server extension enable dask_labextension && \
     rm -rf ~/.cache/pip
 
-RUN apt-get clean && apt-get autoclean && apt-get autoremove -y && \
-    rm -rf /var/lib/apt/lists/*
+# Cleanup package caches
+RUN if command -v apt-get >/dev/null; then \
+        apt-get clean && apt-get autoclean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*; \
+    else \
+        dnf clean all && rm -rf /var/cache/dnf; \
+    fi
 
 EXPOSE 8888
 CMD ["/bin/bash"]
@@ -135,9 +175,6 @@ FROM sdk-base AS nvc
 
 # Make devito env vars file and extras
 ADD docker/nvdashboard.json /app/nvdashboard.json
-
-# mpi4py
-ENV MPI4PY_FLAGS='source $HPCSDK_HOME/comm_libs/hpcx/latest/hpcx-init.sh && hpcx_load && CC=nvc CFLAGS="-noswitcherror -tp=px"'
 
 ENV DEVITO_ARCH="nvc"
 ENV DEVITO_PLATFORM="nvidiaX"
